version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
        - "3306:3306"
    expose:
      - "3306"
    volumes:
        - db_data:/var/lib/mysql
        - ./sql/init.sql:/docker-entrypoint-initdb.d/1.sql
        - ./sql/data.sql:/docker-entrypoint-initdb.d/2.sql

volumes:
    db_data:

